# تحديد مسار وبروتوكول الاتصال بقاعدة بيانات MySQL واسم قاعدة البيانات (productsdb)
spring.datasource.url=jdbc:mysql://localhost:3306/productsdb

# تحديد اسم المستخدم الخاص بقاعدة البيانات (الافتراضي هو root)
spring.datasource.username=root

# تحديد كلمة السر الخاصة بقاعدة البيانات للدخول والتوصيل
spring.datasource.password=hossamhamade1234